stages:          # List of stages for jobs, and their order of execution
  - check_publiccode
  
publiccode:
    stage: check_publiccode
    allow_failure: true
    script:
      - docker run -i italia/publiccode-parser-go /dev/stdin < publiccode.yml  