---

home_page_title: Flyimg

#debug
debug: false

#Number of days for header cache expires `max_age`
# impostato da Lorello per requisito comuni
header_cache_days: 365

#options separator "," by default
options_separator: ","

#Security: Signature generation
# security key
security_key: ""
# secret Initialization vector(IV)
security_iv: ""

# restrict domains, false by default
restricted_domains: false

# if restricted_domains is enabled, put whitelist domains here
#whitelist_domains:
#    - domain-1.com
#    - domain-2.com

# Default storage system is local, to use use AWS S3, change this param to s3
storage_system: local
#storage_system: "s3"
# Number of threads for Imagemagick to use
# thread: 5

#Extra options for the header sent to source image server, as some servers requires the User-Agent.
header_extra_options: 'User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; rv:2.2) Gecko/20110201'

#List of request header to forward to source image server (example Authorization)
forward_request_headers: [Authorization]

# Keys used in url to match options. Ex: q_80,w_200,h_100
options_keys:
  moz: mozjpeg
  q: quality
  o: output
  unsh: unsharp
  sh: sharpen
  blr: blur
  fc: face-crop
  fcp: face-crop-position
  fb: face-blur
  w: width
  h: height
  c: crop
  bg: background
  st: strip
  rz: resize
  g: gravity
  f: filter
  r: rotate
  sc: scale
  sf: sampling-factor
  rf: refresh
  smc: smart-crop
  ett: extent
  par: preserve-aspect-ratio
  pns: preserve-natural-size
  webpl: webp-lossless
  gf: gif-frame
  e: extract
  p1x: extract-top-x
  p1y: extract-top-y
  p2x: extract-bottom-x
  p2y: extract-bottom-y
  pdfp: pdf-page-number
  tm: time
  clsp: colorspace
  mnchr: monochrome

#Default options values
default_options:
  mozjpeg: 1
  quality: 90
  output: auto
  unsharp: null
  sharpen: null
  blur: null
  face-crop: 0
  face-crop-position: 0
  face-blur: 0
  width: null
  height: null
  crop: null
  background: null
  strip: 1
  resize: null
  gravity: Center
  filter: Lanczos
  rotate: null
  scale: null
  sampling-factor: 1x1
  refresh: false
  smart-crop: false
  extent: null
  preserve-aspect-ratio: 1
  preserve-natural-size: 1
  webp-lossless: 0
  gif-frame: 0
  extract: null
  extract-top-x: null
  extract-top-y: null
  extract-bottom-x: null
  extract-bottom-y: null
  pdf-page-number: 1
  time: '00:00:01'
  colorspace: 'sRGB'
  monochrome: null

# nuove opzioni versione 2+

# https://flyimg.io/configuration/#enable_cronjob_cleanup
# occhio che e' attivo di default, e pulisce ogni 5 ore
enable_cronjob_cleanup: true

# cronjob_cleanup_interval
# Defaults to: 0 */5 * * *

#
# disable_cache
# when set to true the generated image will be deleted from the cache in web/upload and served directly in the response
# Defaults to: false
disable_cache: false

# enable_webp, Defaults to: true
# enable_avif, Defaults to: true
# Attenzione, se si abilita avif capita che immagini tipo
# https://s3-eu-west-1.amazonaws.com/static.opencity.opencontent.it/var/masullas/storage/images/3330-2-ita-IT/Homepage_header_logo.png
# vengano date in JPG con rendering errato, quindi meglio lasciare disattivato
enable_avif: false
# enable_webp: true # attenzione che e' necessario! risulta false by default e non true come dice la documentazione
# When supported by the browser, Webp format will be served as default output (after checking AVIF support)
enable_webp: true
#
# For Avif format: conversion speed parameter for the HEIF library.
heic_speed: 8